version: "3"
services:
  prometheus:
    container_name: prometheus-server
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    user: root
    restart: always
  grafana:
    container_name: grafana-server
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    user: root
    restart: always
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  nginx-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - 9113:9113
    entrypoint: nginx-prometheus-exporter -nginx.scrape-uri=http://nginx/stub_status
    restart: always
    depends_on:
      - nginx
