apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            # Adminユーザー名／パスワードの設定
            - name: GF_PATHS_CONFIG
              value: /etc/ini/admin_user_password.ini
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            # データソースの設定
            - name: grafana-datasource-config
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            # Adminユーザー名／パスワードの設定
            - name: grafana-admin-config
              mountPath: /etc/ini
              readOnly: true
      # 定義したConfigMapをvolumesとして宣言
      volumes:
        - name: grafana-datasource-config
          configMap:
            name: grafana-config
            items:
              - key: datasource.yaml
                path: datasource.yaml
        - name: grafana-admin-config
          configMap:
            name: grafana-config
            items:
              - key: admin_user_password.ini
                path: admin_user_password.ini
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  # GrafanaのAdminユーザー名／パスワード
  admin_user_password.ini: |
    [security]
    admin_user = admin
    admin_password = admin
  # Grafanaに表示するデータソースの設定
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090 # Prometheuseのエンドポイント
