apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
  name: node-exporter
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app: node-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-exporter
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:latest
          ports:
            - containerPort: 9100
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
